name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: sudo sh setup.sh
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build -DGTEST_ROOT=/usr/local/include/gtest/ -DGTEST_LIBRARY=/usr/local/lib/libgtest.a
    - name: test
      run: cd build && ctest --verbose
